bin/common/config.py, bin/public/iptables.py
=> Fixed iptables-setup to not require an internal name server

bin/common/general.py
=> Adding useragent to wget

bin/common/passwordstore.py, bin/public/iptables.py
=> Passwordstore patch

bin/public/hardening/network.py
Had problems with ipv6 getting enabled on new vm installations.
=> to make sure ipv6 gets disabled

bin/common/augeas.py, bin/public/installSssd.py
Bug fixes, objectification of augeas and removing advanced path support since that's already supported in augeas.
=> Sssd update augeas

bin/public/installES.py, bin/public/installJava.py, bin/public/installSonar.py
This will download and install sonar
=> Installing Sonar

bin/public/installES.py, bin/public/installJava.py
Think the best java installation and elasticsearch installation
=> Es BASE and java

bin/vagrant-provision
Fixat så nu kan man köra "vagrant up " och den fungerar med syco.
=> making syco work at once

bin/common/config.py, bin/public/installBind.py
Added support for multiple internal DNS servers and started preferring back net for internal DNS
=> Move dns to back net and support multiple

var/logrotate/httpd, var/logrotate/syslog
=> Fixed a few line-ins and corrected archive path for httpd rotation

bin/public/installGlassfish4.py
Need to update "handlerServices" attribute for that, see https://java.net/jira/browse/GLASSFISH-20718
=> Glassfish4 logging to syslog

bin/common/password.py, bin/public/installHaproxy.py, bin/public/iptables.py, usr/mod-template/etc/minimal-general.cfg, usr/mod-template/etc/minimal-install.cfg, usr/mod-template/etc/minimal-passwordstore
to handle active/backup configs.
Based on changes by @Kemani.
=> Refactoring of install ha proxy and added feature 

lib/nagios/plugins_nrpe/check_hparray
The sudo command for root broke our nrpe checks
=> Removed sudo -u root from script

bin/public/installRsyslogd.py
Adding back missing function call.
Fixes #242
=> Setup rsyslogd config files

bin/common/scopen.py
Can be useful for example when you want to inject private/public keys into config files (will need this for Kenobi config)
=> Control output from scOpen methods

bin/common/config.py, bin/public/installSyco.py
... also added a new feature in config to list all commands for a host
=> Changed swappiness to 0 on all hosts

bin/common/general.py, bin/common/scopen.py, bin/common/ssh.py
Features:
- Wait for root login
- Retrieve files from syco server including waiting for files to be available
=> New general features

bin/public/installDocker.py, bin/public/installSyco.py, bin/public/iptables.py
... and include iptables custom port support to haproxy
=> Moved yum proxy settings to syco install

bin/public/installESpower.py
Some tuning of the code. It hasn't been tested. But I have a strong feeling that the current installation won't really work 100% as is anyway. The installation of ES needs more refactoring and testing. Maybe as part of next step of the ES.
=> Elastic search

bin/public/installHaproxy.py
Without backnet, eth0 is the only NIC
=> Updated haproxy to support having no backnet

bin/public/installNrpe.py
Password looks incorrect in terminal output when installation sets it but it is set correctly in common.cfg
=> Works when pass contains &

bin/public/installNrpe.py, lib/nagios/plugins_nrpe/check_hparray
Also cleaned up the NRPE installation a bit.
Dependency installation for clamscan is not needed since it installed the same packages that are installed during NRPE base installation.
=> Updating raid plugin

bin/public/installNrpe.py
Blank space broke EOF... Lets live with unindented code for now.
=> Removed invalid spacing
